version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-user-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  react:
    driver: bridge