version: '3.3'

services:
  # app:
  #   build: 
  #     context: node
  #   container_name: app
  #   networks:
  #     - node-network
  #   volumes:
  #     - ./node:/usr/src/app
  #   tty: true
  #   ports:
  #     - "3000:3000"

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'db'
      MYSQL_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  db:
    driver: local